alertmanager:
  enabled: true
  alertmanagerSpec:
    logLevel: info
    replicas: 1
    tolerations:
      - key: "vendor"
        operator: "Equal"
        value: "cosmotech"
        effect: "NoSchedule"
    nodeSelector:
      "cosmotech.com/tier": "monitoring"
    resources:
      limits:
        cpu: 1
        memory: 1Gi
      requests:
        cpu: 1
        memory: 1Gi
    image:
      registry: ${IMAGE_REGISTRY}
      repository: cosmotech/prometheus-alertmanager

grafana:
  enabled: true
  adminPassword: ${PROMETHEUS_ADMIN_PASSWORD}
  defaultDashboardsEnabled: true
  persistence:
    enabled: true
    type: pvc
    existingClaim: ${PERSISTENCE_PVC_GRAFANA}
    storageClassName: ${PERSISTENCE_STORAGE_CLASS}
    size: "${PERSISTENCE_SIZE_GRAFANA}Gi"
    accessModes:
      - ReadWriteOnce
  sidecar:
    image:
      repository: cosmotech/k8s-sidecar
      pullPolicy: IfNotPresent
    dashboards:
      multicluster:
        enabled: true
        label: grafana_dashboard
        labelValue: "1"
        searchNamespace: ALL
        annotations: {}
        global:
          enabled: false
        etcd:
          enabled: false
    datasources:
      alertmanager:
        enabled: true
        uid: alertmanager
        handleGrafanaManagedAlerts: false
        implementation: prometheus
  grafana.ini:
    server:
      domain: ${COSMOTECH_CLUSTER_DOMAIN}
      root_url: "%(protocol)s://%(domain)s/monitoring"
      serve_from_sub_path: true
  ingress:
    enabled: true
    ingressClassName: traefik
    path: "/monitoring"
    hosts:
      - ${COSMOTECH_CLUSTER_DOMAIN}
    tls:
      - secretName: "letsencrypt-prod"
        hosts:
          - ${COSMOTECH_CLUSTER_DOMAIN}
  plugins:
    - redis-datasource
  additionalDataSources:
    - name: cosmotech-redis
      orgId: 1
      type: redis-datasource
      access: proxy
      url: redis://cosmotechredis-redis-master.redis.svc.cluster.local:6379
      basicAuth: false
      withCredentials: false
      isDefault: false
      version: 1
      editable: false
      secureJsonData:
        password: ${REDIS_ADMIN_PASSWORD}
  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
        - name: default
          orgId: 1
          folder: ''
          type: file
          disableDeletion: false
          editable: true
          options:
            path: /var/lib/grafana/dashboards/default
  dashboards:
    default:
      redis:
        gnetId: 12776
        revision: 2
        datasource: cosmotech-redis
      argo:
        gnetId: 14136
        revision: 1
        datasource: Prometheus
      nginx:
        gnetId: 9614
        revision: 1
        datasource: Prometheus
      postgresql:
        gnetId: 9628
        revision: 7
        datasource: Prometheus
      certmanager:
        gnetId: 11001
        revision: 1
        datasource: Prometheus
      csm_licensing:
        url: "https://raw.githubusercontent.com/Cosmo-Tech/azure-platform-deployment-tools/main/grafana/cosmotech_licensing/v8/cosmotech_licensing.json"
      csm_licensing_light:
        url: "https://raw.githubusercontent.com/Cosmo-Tech/azure-platform-deployment-tools/main/grafana/cosmotech_licensing/v8/cosmotech_licensing_light.json"
      csm_customer_success:
        url: "https://raw.githubusercontent.com/Cosmo-Tech/azure-platform-deployment-tools/main/grafana/customer_success/v1/customer_success.json"
      csm_api:
        url: "https://raw.githubusercontent.com/Cosmo-Tech/azure-platform-deployment-tools/main/grafana/cosmotech_api/v1/cosmotech_api.json"
  downloadDashboardsImage:
    repository: cosmotech/os-shell-iamguarded
    tag: latest
    pullPolicy: IfNotPresent
  initChownData:
    image:
      repository: cosmotech/os-shell-iamguarded
      tag: latest
      pullPolicy: IfNotPresent
  image:
    repository: cosmotech/grafana
    tag: "13"
    pullPolicy: IfNotPresent
  imagePullSecrets:
    - name: ${IMAGE_REGISTRY_AUTH_SECRET}
  tolerations:
    - key: "vendor"
      operator: "Equal"
      value: "cosmotech"
      effect: "NoSchedule"
  nodeSelector:
    "cosmotech.com/tier": "monitoring"

prometheus:
  enabled: true
  serviceAccount:
    create: true
    name: prometheus
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    logLevel: info
    retention: "15d"
    storage: {}
    volumes:
      - name: prometheus-volume
        persistentVolumeClaim:
          claimName: ${PERSISTENCE_PVC_PROMETHEUS}
    resources:
      limits:
        cpu: 1
        memory: 1Gi
      requests:
        cpu: 1
        memory: 1Gi
    replicas: 1
    image:
      registry: ${IMAGE_REGISTRY}
      repository: cosmotech/prometheus
      tag: "3"
    tolerations:
      - key: "vendor"
        operator: "Equal"
        value: "cosmotech"
        effect: "NoSchedule"
    nodeSelector:
      "cosmotech.com/tier": "monitoring"
    initContainers:
      - name: volume-permissions
        image: ${IMAGE_REGISTRY}/cosmotech/os-shell-iamguarded
        command: ["sh", "-c", "chown -R 1000:1000 /prometheus || true"]
        volumeMounts:
          - name: prometheus-volume
            mountPath: /prometheus

kubeApiServer:
  enabled: true
kubelet:
  enabled: true
kubeControllerManager:
  enabled: true
coreDns:
  enabled: true
kubeEtcd:
  enabled: true
kubeScheduler:
  enabled: true
kubeStateMetrics:
  enabled: true

kube-state-metrics:
  image:
    repository: cosmotech/kube-state-metrics
    tag: latest
    distroless: false
  tolerations:
    - key: "vendor"
      operator: "Equal"
      value: "cosmotech"
      effect: "NoSchedule"
  nodeSelector:
    "cosmotech.com/tier": "monitoring"

prometheusOperator:
  tolerations:
    - key: "vendor"
      operator: "Equal"
      value: "cosmotech"
      effect: "NoSchedule"
  nodeSelector:
    "cosmotech.com/tier": "monitoring"
  prometheusConfigReloader:
    image:
      registry: ${IMAGE_REGISTRY}
      repository: cosmotech/prometheus-config-reloader
  admissionWebhooks:
    patch:
      enabled: true
      tolerations:
        - key: "vendor"
          operator: "Equal"
          value: "cosmotech"
          effect: "NoSchedule"
      nodeSelector:
        "cosmotech.com/tier": "monitoring"
      image:
        registry: ${IMAGE_REGISTRY}
        repository: cosmotech/kube-webhook-certgen

nodeExporter:
  enabled: true

prometheus-node-exporter:
  image:
    repository: cosmotech/prometheus-node-exporter
    tag: latest
    distroless: false
  tolerations:
    - key: "vendor"
      operator: "Equal"
      value: "cosmotech"
      effect: "NoSchedule"
  # nodeSelector:
  #   "cosmotech.com/tier": "monitoring"

defaultRules:
  create: true

kubernetesServiceMonitors:
  enabled: true

windowsMonitoring:
  enabled: false

global:
  imageRegistry: ${IMAGE_REGISTRY}
  imagePullSecrets:
    - name: ${IMAGE_REGISTRY_AUTH_SECRET}