externalURL: http://${CLUSTER_DOMAIN}
exposureType: ingress
service:
  type: ClusterIP
ingress:
  core:
    enabled: true
    ingressClassName: traefik
    hostname: ${CLUSTER_DOMAIN}
    path: /harbor
    pathType: Prefix
    tls: false
    selfSigned: false
tolerations:
  - key: vendor
    operator: Equal
    value: cosmotech
    effect: NoSchedule
persistence:
  enabled: true
  volumePermissions:
    enabled: true
  resourcePolicy: "keep"
  persistentVolumeClaim:
    registry:
      existingClaim: "${PERSISTENCE_REGISTRY_PVC}"
      subPath: registry
    jobservice:
      existingClaim: "${PERSISTENCE_JOBSERVICE_PVC}"
      subPath: jobservice
registry:
  storage:
    filesystem:
      rootdirectory: /harbor-data
  image:
    registry: ${IMAGE_REGISTRY}
    repository: ${HARBOR_IMAGE_REPOSITORY_PREFIX}-registry-iamguarded
    tag: ${HARBOR_IMAGE_TAG}
    pullPolicy: IfNotPresent
  server:
    image:
      registry: ${IMAGE_REGISTRY}
      repository: ${HARBOR_IMAGE_REPOSITORY_PREFIX}-registry-iamguarded
      tag: ${HARBOR_IMAGE_TAG}
      pullPolicy: IfNotPresent
    resourcesPreset: "nano"
  controller:
    image:
      registry: ${IMAGE_REGISTRY}
      repository: ${HARBOR_IMAGE_REPOSITORY_PREFIX}-registryctl-iamguarded
      tag: ${HARBOR_IMAGE_TAG}
      pullPolicy: IfNotPresent
    resourcesPreset: "nano"
  nodeSelector:
    "cosmotech.com/tier": "db"
  tolerations:
    - key: vendor
      operator: Equal
      value: cosmotech
      effect: NoSchedule

externalDatabase:
  host: harbor-postgresql-rw.${NAMESPACE}.svc.cluster.local
  port: 5432
  user: harbor
  existingSecret: "${SECRET}"
  existingSecretPasswordKey: password
  coreDatabase: harbor_db
  sslmode: disable
postgresql:
  enabled: false

externalRedis:
  host: harbor-redis-master.${NAMESPACE}.svc.cluster.local
  port: 6379
redis:
  enabled: false

portal:
  replicas: 1
  image:
    registry: ${IMAGE_REGISTRY}
    repository: ${HARBOR_IMAGE_REPOSITORY_PREFIX}-portal-iamguarded
    tag: ${HARBOR_IMAGE_TAG}
    pullPolicy: IfNotPresent
  nodeSelector:
    "cosmotech.com/tier": "services"
  tolerations:
    - key: vendor
      operator: Equal
      value: cosmotech
      effect: NoSchedule
  resourcesPreset: "nano"

core:
  replicas: 1
  image:
    registry: ${IMAGE_REGISTRY}
    repository: ${HARBOR_IMAGE_REPOSITORY_PREFIX}-core-iamguarded
    tag: ${HARBOR_IMAGE_TAG}
    pullPolicy: IfNotPresent
  nodeSelector:
    "cosmotech.com/tier": "services"
  tolerations:
    - key: vendor
      operator: Equal
      value: cosmotech
      effect: NoSchedule
  resourcesPreset: "nano"

jobservice:
  replicas: 1
  image:
    registry: ${IMAGE_REGISTRY}
    repository: ${HARBOR_IMAGE_REPOSITORY_PREFIX}-jobservice-iamguarded
    tag: ${HARBOR_IMAGE_TAG}
    pullPolicy: IfNotPresent
  nodeSelector:
    "cosmotech.com/tier": "db"
  tolerations:
    - key: vendor
      operator: Equal
      value: cosmotech
      effect: NoSchedule
  resourcesPreset: "nano"

exporter:
  enabled: true
  core:
      host: harbor-core.${NAMESPACE}.svc.cluster.local
      port: 8080  
  image:
    registry: ${IMAGE_REGISTRY}
    repository: ${HARBOR_IMAGE_REPOSITORY_PREFIX}-exporter-iamguarded
    tag: ${HARBOR_IMAGE_TAG}
    pullPolicy: IfNotPresent
  nodeSelector:
    "cosmotech.com/tier": "services"
  tolerations:
    - key: vendor
      operator: Equal
      value: cosmotech
      effect: NoSchedule
  resourcesPreset: "nano"

chartmuseum:
  enabled: false

notary:
  enabled: false

trivy:
  enabled: false

nginx:
  enabled: true
  image:
    registry: ${IMAGE_REGISTRY}
    repository: cosmotech/nginx-iamguarded
    pullPolicy: IfNotPresent
  resourcesPreset: "nano"

existingSecret: "${SECRET}"
existingSecretAdminPasswordKey: "${HARBOR_ADMIN_PASSWORD}"
logLevel: info
metrics:
  enabled: true
internalTLS:
  enabled: false

global:
  imageRegistry: ${IMAGE_REGISTRY}
  imagePullSecrets:
  - name: ${IMAGE_REGISTRY_AUTH_SECRET}