architecture: "standalone" 

auth:
  enabled: false

metrics:
  enabled: true
  image:
    repository: ${IMAGE_REPOSITORY_PREFIX}/prometheus-redis-exporter-iamguarded
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
  resourcesPreset: "nano"

master:
  persistence:
    enabled: true
    existingClaim: "${PERSISTENCE_REDIS_PVC}"
    storageClass: "${PERSISTENCE_STORAGE_CLASS}"
  volumePermissions:
    enabled: true
  service:
    type: ClusterIP
    port: 6379
  nodeSelector:
    "cosmotech.com/tier": "db"
  tolerations:
    - key: "vendor"
      operator: "Equal"
      value: "cosmotech"
      effect: "NoSchedule"
  resourcesPreset: "nano"

replica:
  replicaCount: 0
  persistence:
    enabled: false
  resourcesPreset: "nano"

volumePermissions:
  enabled: true
  image:
    repository: ${IMAGE_REPOSITORY_PREFIX}/${GENERIC_SHELL_IMAGE_NAME}
    tag: ${GENERIC_SHELL_IMAGE_TAG}
    pullPolicy: IfNotPresent

image:
  repository: ${IMAGE_REPOSITORY_PREFIX}/redis
  tag: ${REDIS_IMAGE_TAG}
  pullPolicy: IfNotPresent

global:
  imageRegistry: ${IMAGE_REGISTRY}
  imagePullSecrets:
  - name: ${IMAGE_REGISTRY_AUTH_SECRET}