#!/bin/sh

# Stop script if missing dependency
required_commands="terraform aws jq"
for command in $required_commands; do
    if [ -z "$(command -v $command)" ]; then
        echo "error: required command not found: \e[91m$command\e[97m"
        exit 1
    fi
done

# Get values from terraform.tfvars
get_var_value() {
    local file=$1
    local variable=$2
    grep -E "^[[:space:]]*$variable[[:space:]]*=[[:space:]]*" "$file" | sed -E 's/.*=[[:space:]]*"(.*)".*/\1/' | head -n 1
}

cloud_provider="$(get_var_value terraform.tfvars cloud_provider)"
region="$(get_var_value terraform.tfvars region)"
shared="$(get_var_value terraform.tfvars shared)"
backend_state_prefix="$(get_var_value terraform.tfvars backend_state_prefix)"


# THIS IS THE KEY: cluster state prefix depends on cloud
case "$cloud_provider" in
  azure) backend_state_prefix="$backend_state_prefix" ;;
  aws)   backend_state_prefix="$backend_state_prefix"   ;;
  gcp)   backend_state_prefix="$backend_state_prefix"   ;;
  *)     echo "error: unknown cloud_provider: $cloud_provider"; exit 1 ;;
esac

state_file_name="tfstate-shared-$shared"

# Clear old Terraform files
rm -rf .terraform* terraform.tfstate* backend.tf data.tf 2>/dev/null || true

# ===================================================================
# 1. Generate backend.tf (your own state)
# ===================================================================
cat > backend.tf <<EOF
terraform {
  backend "azurerm" {
    resource_group_name  = "cosmotechstates"
    storage_account_name = "cosmotechstates"
    container_name       = "cosmotechstates"
    key                  = "$state_file_name"
  }
}
EOF

case "$cloud_provider" in
  azure)
    cat > backend.tf <<EOF
provider "azurerm" {
  features {}
  subscription_id = var.azure_subscription_id
  tenant_id       = var.azure_entra_tenant_id
}
terraform {
  backend "azurerm" {
    key                  = "$state_file_name"
    storage_account_name = "cosmotechstates"
    container_name       = "cosmotechstates"
    resource_group_name  = "cosmotechstates"
  }
}
variable "azure_subscription_id" { type = string }
variable "azure_entra_tenant_id" { type = string }
EOF
    ;;

  aws)
    cat > backend.tf <<EOF
provider "aws" {
  region = var.region
}
terraform {
  backend "s3" {
    key    = "$state_file_name"
    bucket = "cosmotech-states"
    region = "$region"
  }
}
EOF
    ;;

  gcp)
    cat > backend462.tf <<EOF
provider "google" {
  project = var.project_id
  region  = var.region
}
terraform {
  backend "gcs" {
    bucket = "cosmotech-states"
    prefix = "$state_file_name"
  }
}
variable "project_id" { type = string }
EOF
    ;;
esac
# ===================================================================
# 2. Generate ONLY the data sources needed + remote state for CLUSTER
# ===================================================================
cat > data.tf <<EOF
# AUTO-GENERATED by run.sh – do not edit manually
# Cloud provider: $cloud_provider

data "terraform_remote_state" "terraform_cluster" {
  backend = $(case "$cloud_provider" in
    gcp)   echo '"gcs"'     ;;
    aws)   echo '"s3"'      ;;
    azure) echo '"azurerm"' ;;
  esac)

  config = {
$(case "$cloud_provider" in
  gcp)
    cat <<GCP
    bucket = "cosmotech-states"
    prefix = "$backend_state_prefix"
GCP
    ;;
  aws)
    cat <<AWS
    bucket = "cosmotech-states"
    key    = "$backend_state_prefix"
    region = "$region"
AWS
    ;;
  azure)
    cat <<AZURE
    storage_account_name = "cosmotechstates"
    container_name       = "cosmotechstates"
    key                  = "$backend_state_prefix"
    resource_group_name  = "cosmotechstates"
AZURE
    ;;
esac
    )
  }
}

$(case "$cloud_provider" in
  gcp)
    echo 'data "google_client_config" "current" {}'
    ;;
  aws)
    cat <<AWS
data "aws_eks_cluster" "this" {
  name = data.terraform_remote_state.terraform_cluster.outputs.cluster_name
}
data "aws_eks_cluster_auth" "this" {
  name = data.aws_eks_cluster.this.name
}
AWS
    ;;
  azure)
    echo 'data "azurerm_client_config" "current" {}'
    ;;
esac)
EOF
# ===================================================================
# Run Terraform
# ===================================================================
terraform init -upgrade -reconfigure
# terraform plan -var-file="terraform.tfvars"
terraform apply -auto-approve

exit 0