# AUTO-GENERATED by run.sh – do not edit manually
# Cloud provider: azure

data "terraform_remote_state" "terraform_cluster" {
  backend = "azurerm"

  config = {
    storage_account_name = "cosmotechstates"
    container_name       = "cosmotechstates"
    key                  = "tfstate-cluster-aks-assetaip-dev"
    resource_group_name  = "cosmotechstates"
  }
}

data "azurerm_client_config" "current" {}
