api_dns_name   = "cluster.gcp.platform.cosmotech.com"
cloud_provider = "gcp"
customer_name  = "cosmotech"
email          = "platform@cosmotech.com"
project_id     = "gke-test-devops"
project_name   = "platform"
project_stage  = "dev"
region         = "europe-west6"