auth:
  enabled: true
  username: admin
  existingSecret: "${SUPERSET_SECRET_NAME}"

beat:
  enabled: false

defaultInitContainers:
  waitForDB:
    enabled: true
    resourcesPreset: nano
  waitForRedis:
    enabled: true
    resourcesPreset: nano

existingConfigmap: "${CONFIGMAP_NAME}"

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/hsts: "false"
    ## Define timeout to allow long-running queries
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "${SUPERSET_CONNECT_TIMEOUT}"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "${SUPERSET_QUERY_TIMEOUT}"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "${SUPERSET_QUERY_TIMEOUT}"
    ## Define body sizes for large data file exchanges.
    nginx.ingress.kubernetes.io/client_max_body_size: "${SUPERSET_MAX_FILE_SIZE}"
    nginx.ingress.kubernetes.io/proxy-body-size: "${SUPERSET_MAX_FILE_SIZE}"
    nginx.ingress.kubernetes.io/client-body-buffer-size: "${SUPERSET_BUFFER_SIZE}"
  extraTls:
  - hosts:
      - "${SUPERSET_CLUSTER_DOMAIN}"
    secretName: letsencrypt-prod
  path: /
  pathType: Prefix
  hostname: "${SUPERSET_CLUSTER_DOMAIN}"
  ingressClassName: nginx
  selfSigned: false


# ingress:
#   annotations:
#     kubernetes.io/ingress.class: nginx
#     cert-manager.io/cluster-issuer: letsencrypt-prod
#     nginx.ingress.kubernetes.io/hsts: "false"
#     ## Define timeout to allow long-running queries
#     nginx.ingress.kubernetes.io/proxy-connect-timeout: "${SUPERSET_CONNECT_TIMEOUT}"
#     nginx.ingress.kubernetes.io/proxy-read-timeout: "${SUPERSET_QUERY_TIMEOUT}"
#     nginx.ingress.kubernetes.io/proxy-send-timeout: "${SUPERSET_QUERY_TIMEOUT}"
#     ## Define body sizes for large data file exchanges.
#     nginx.ingress.kubernetes.io/client_max_body_size: "${SUPERSET_MAX_FILE_SIZE}"
#     nginx.ingress.kubernetes.io/proxy-body-size: "${SUPERSET_MAX_FILE_SIZE}"
#     nginx.ingress.kubernetes.io/client-body-buffer-size: "${SUPERSET_BUFFER_SIZE}"
#   apiVersion: ""
#   enabled: true
#   extraHosts: []
#   extraPaths: []
#   extraRules: []
#   extraTls:
#   - hosts:
#       - "${SUPERSET_CLUSTER_DOMAIN}"
#     secretName: letsencrypt-prod
#   path: /
#   pathType: Prefix
#   hostname: "${SUPERSET_CLUSTER_DOMAIN}"
#   ingressClassName: nginx
#   secrets: []
#   selfSigned: false
#   tls: []


postgresql:
  enabled: true
  architecture: standalone
  auth:
    database: bitnami_superset
    enablePostgresUser: true
    existingSecret: "${SUPERSET_POSTGRESQL_SECRET_NAME}"
    username: bn_superset
  image:
    registry: ${IMAGE_REGISTRY}
    repository: ${POSTGRESQL_IMAGE_REPOSITORY}
    tag: ${POSTGRESQL_IMAGE_TAG}
    pullPolicy: IfNotPresent
  primary:
    nodeSelector:
      "cosmotech.com/tier": "db"
    tolerations:
      - effect: NoSchedule
        key: vendor
        operator: Equal
        value: cosmotech
    resourcesPreset: nano
    service:
      ports:
        postgresql: 5432
    persistence:
      enabled: true
      existingClaim: "${PERSISTENCE_POSTGRESQL_PVC}"

redis:
  enabled: true
  architecture: standalone
  auth:
    enabled: true
    existingSecret: "${SUPERSET_REDIS_SECRET_NAME}"
    username: default
  image:
    registry: ${IMAGE_REGISTRY}
    # repository: cosmotech/redis
    repository: cosmotech/redis-server-iamguarded
    pullPolicy: IfNotPresent
  master:
    nodeSelector:
      "cosmotech.com/tier": "db"
    tolerations:
      - effect: NoSchedule
        key: vendor
        operator: Equal
        value: cosmotech
    resourcesPreset: nano
    service:
      ports:
        redis: 6379
    persistence:
      enabled: true
      existingClaim: "${PERSISTENCE_REDIS_PVC}"
  # command: ["redis-server"]

init:
  enabled: true
  extraEnvVars:
    - name: SUPERSET_OAUTH_PROVIDERS
      valueFrom:
        configMapKeyRef:
          key: oauth-providers
          name: ${OAUTH_PROVIDERS_CONFIGMAP_NAME}
          optional: true
    - name: SUPERSET_SECRET_KEY
      valueFrom:
        secretKeyRef:
          key: secret-key
          name: ${SUPERSET_SECRET_KEY_NAME}
    - ${PYTHON_REQUIREMENTS_EXTRA_ENV_VARS}
  initContainers:
    ${PYTHON_REQUIREMENTS_INIT_CONTAINER}
  extraVolumes:
    ${PYTHON_REQUIREMENTS_INIT_CONTAINER_VOLUMES}
  extraVolumeMounts:
    ${PYTHON_REQUIREMENTS_INIT_CONTAINER_VOLUME_MOUNTS}
  # extraVolumes:
  #   - PYTHON_REQUIREMENTS_VOLUMES}
  # extraVolumeMounts:
  #   - PYTHON_REQUIREMENTS_VOLUMES_MOUNTS}
  podSecurityContext:
    enabled: true
    fsGroup: 1001
    runAsUser: 1001
  resourcesPreset: medium

web:
  extraEnvVars:
    - name: SUPERSET_OAUTH_PROVIDERS
      valueFrom:
        configMapKeyRef:
          key: oauth-providers
          name: ${OAUTH_PROVIDERS_CONFIGMAP_NAME}
          optional: true
    - name: SUPERSET_SECRET_KEY
      valueFrom:
        secretKeyRef:
          key: secret-key
          name: ${SUPERSET_SECRET_KEY_NAME}
    - ${PYTHON_REQUIREMENTS_EXTRA_ENV_VARS}
  initContainers:
    ${PYTHON_REQUIREMENTS_INIT_CONTAINER}
  extraVolumes:
    ${PYTHON_REQUIREMENTS_INIT_CONTAINER_VOLUMES}
  extraVolumeMounts:
    ${PYTHON_REQUIREMENTS_INIT_CONTAINER_VOLUME_MOUNTS}
  # extraVolumes:
  #   - PYTHON_REQUIREMENTS_VOLUMES}
  # extraVolumeMounts:
  #   - PYTHON_REQUIREMENTS_VOLUMES_MOUNTS}
  podSecurityContext:
    enabled: true
    fsGroup: 1001
    runAsUser: 1001
  nodeSelector:
    cosmotech.com/tier: services
  tolerations: 
  - effect: NoSchedule
    key: vendor 
    operator: Equal 
    value: cosmotech
    resourcesPreset: nano

worker:
  command:
  - celery
  - worker
  - --concurrency=2
  - --loglevel=INFO
  # containerSecurityContext:
  #   runAsNonRoot: true
  extraEnvVars:
    - name: REDIS_PASSWORD
      valueFrom:
        secretKeyRef:
          key: redis-password
          name: ${SUPERSET_REDIS_SECRET_NAME}
    - name: CELERY_BROKER_URL
      value: redis://default:$(REDIS_PASSWORD)@superset-redis-master:6379/0
    - name: CELERY_RESULT_BACKEND
      value: redis://default:$(REDIS_PASSWORD)@superset-redis-master:6379/0
    - name: SUPERSET_OAUTH_PROVIDERS
      valueFrom:
        configMapKeyRef:
          key: oauth-providers
          name: ${OAUTH_PROVIDERS_CONFIGMAP_NAME}
          optional: true
    - name: SUPERSET_SECRET_KEY
      valueFrom:
        secretKeyRef:
          key: secret-key
          name: ${SUPERSET_SECRET_KEY_NAME}
    - ${PYTHON_REQUIREMENTS_EXTRA_ENV_VARS}
  initContainers:
    ${PYTHON_REQUIREMENTS_INIT_CONTAINER}
  extraVolumes:
    ${PYTHON_REQUIREMENTS_INIT_CONTAINER_VOLUMES}
  extraVolumeMounts:
    ${PYTHON_REQUIREMENTS_INIT_CONTAINER_VOLUME_MOUNTS}
  # extraVolumes:
  #   - PYTHON_REQUIREMENTS_VOLUMES}
  # extraVolumeMounts:
  #   - PYTHON_REQUIREMENTS_VOLUMES_MOUNTS}
  podSecurityContext:
    enabled: true
    fsGroup: 1001
    runAsUser: 1001
  livenessProbe:
    enabled: true
  readinessProbe:
    enabled: true
  replicaCount: 1
  resources:
    limits:
      cpu: 4
      memory: 6Gi
    requests:
      cpu: 3
      memory: 4Gi
  nodeSelector:
    cosmotech.com/tier: services
  tolerations: 
  - effect: NoSchedule
    key: vendor 
    operator: Equal 
    value: cosmotech

image:
  # registry: ghcr.io
  # repository: cosmo-tech/superset
  # tag: latest
  repository: cosmotech/superset-iamguarded
  # repository: cosmotech/superset-iamguarded-pip
  pullPolicy: IfNotPresent
  debug: true

global:
  storageClass: "${PERSISTENCE_STORAGE_CLASS}"
  imageRegistry: ${IMAGE_REGISTRY}
  imagePullSecrets:
    - name: ${IMAGE_REGISTRY_AUTH_SECRET}
