installCRDs: true

nodeSelector:
  cosmotech.com/tier: services
tolerations:
  - key: "vendor"
    operator: "Equal"
    value: "cosmotech"
    effect: "NoSchedule"
  - key: "cosmotech.com/tier"
    operator: "Equal"
    value: "services"
    effect: "NoSchedule"
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi
serviceAccount:
  create: false
  annotations: |
    ${SERVICE_ANNOTATIONS}

cainjector:
  podLabels:
    networking/traffic-allowed: "yes"
  nodeSelector:
    cosmotech.com/tier: services
  tolerations:
    - key: "vendor"
      operator: "Equal"
      value: "cosmotech"
      effect: "NoSchedule"
    - key: "cosmotech.com/tier"
      operator: "Equal"
      value: "services"
      effect: "NoSchedule"
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi
  image:
    repository: ${IMAGE_REPOSITORY_PREFIX}-cainjector-iamguarded
    tag: ${IMAGE_TAG}
    pullPolicy: IfNotPresent

controller:
  podLabels:
    networking/traffic-allowed: "yes"
  nodeSelector:
    cosmotech.com/tier: services
  tolerations:
    - key: "vendor"
      operator: "Equal"
      value: "cosmotech"
      effect: "NoSchedule"
    - key: "cosmotech.com/tier"
      operator: "Equal"
      value: "services"
      effect: "NoSchedule"
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi
  image:
    repository: ${IMAGE_REPOSITORY_PREFIX}-controller-iamguarded
    tag: ${IMAGE_TAG}
    pullPolicy: IfNotPresent
  acmesolver:
    image:
      repository: ${IMAGE_REPOSITORY_PREFIX}-acmesolver-iamguarded
      tag: ${IMAGE_TAG}
      pullPolicy: IfNotPresent

webhook:
  podLabels:
    networking/traffic-allowed: "yes"
  nodeSelector:
    cosmotech.com/tier: services
  tolerations:
    - key: "vendor"
      operator: "Equal"
      value: "cosmotech"
      effect: "NoSchedule"
    - key: "cosmotech.com/tier"
      operator: "Equal"
      value: "services"
      effect: "NoSchedule"
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi
  image:
    repository: ${IMAGE_REPOSITORY_PREFIX}-webhook-iamguarded
    tag: ${IMAGE_TAG}
    pullPolicy: IfNotPresent

startupapicheck:
  nodeSelector:
    cosmotech.com/tier: services
  tolerations:
    - key: "vendor"
      operator: "Equal"
      value: "cosmotech"
      effect: "NoSchedule"
    - key: "cosmotech.com/tier"
      operator: "Equal"
      value: "services"
      effect: "NoSchedule"
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi

global:
  imageRegistry: ${IMAGE_REGISTRY}
  imagePullSecrets:
    - name: ${IMAGE_REGISTRY_AUTH_SECRET}
