primary:
  persistence:
    enabled: true
    existingClaim: ${PERSISTENCE_PVC}
  nodeSelector:
    cosmotech.com/tier: db
  tolerations:
    - key: vendor
      operator: Equal
      value: cosmotech
      effect: NoSchedule
  resourcesPreset: nano
image:
  repository: cosmotech/postgresql
volumePermissions:
  enabled: true
  image:
    repository: cosmotech/os-shell-iamguarded
    tag: latest
    pullPolicy: IfNotPresent
global:
  imageRegistry: ${IMAGE_REGISTRY}
  imagePullSecrets:
    - name: ${IMAGE_REGISTRY_AUTH_SECRET}
  postgresql:
    auth:
      database: keycloak_db
      username: ${POSTGRES_USER}
      existingSecret: ${KEYCLOAK_SECRET}
      secretKeys:
        userPasswordKey: ${POSTGRES_PASSWORD_SECRET_KEY}
        adminPasswordKey: ${POSTGRES_ADMIN_PASSWORD_SECRET_KEY}