architecture: "standalone" 
auth:
  enabled: false
master:
  persistence:
    enabled: true
    existingClaim: "${PERSISTENCE_REDIS_PVC}"
    storageClass: "${PERSISTENCE_STORAGE_CLASS}"
  volumePermissions:
    enabled: true
  service:
    type: ClusterIP
    port: 6379
  nodeSelector:
    "cosmotech.com/tier": "db"
  tolerations:
    - key: "vendor"
      operator: "Equal"
      value: "cosmotech"
      effect: "NoSchedule"
  resourcesPreset: "nano"
replica:
  replicaCount: 0
  persistence:
    enabled: false
  resourcesPreset: "nano"
image:
  repository: cosmotech/redis-server-iamguarded
  pullPolicy: IfNotPresent
metrics:
  enabled: true
  image:
    repository: cosmotech/prometheus-redis-exporter-iamguarded
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
  resourcesPreset: "nano"
volumePermissions:
  enabled: true
  image:
    repository: cosmotech/os-shell-iamguarded
    tag: latest
    pullPolicy: IfNotPresent
global:
  imageRegistry: ${IMAGE_REGISTRY}
  imagePullSecrets:
    - name: ${IMAGE_REGISTRY_AUTH_SECRET}
  redis:
    password: ""