primary:
  persistence:
    enabled: true
    existingClaim: "${PERSISTENCE_POSTGRESQL_PVC}"
  nodeSelector:
    "cosmotech.com/tier": "db"
  tolerations:
    - key: "vendor"
      operator: "Equal"
      value: "cosmotech"
      effect: "NoSchedule"
  resourcesPreset: "nano"
image:
  # registry: ${IMAGE_REGISTRY}
  repository: cosmotech/postgres-iamguarded
  tag: "16"
volumePermissions:
  enabled: true
  image:
    repository: cosmotech/os-shell-iamguarded
    tag: latest
    pullPolicy: IfNotPresent
global:
  imageRegistry: ${IMAGE_REGISTRY}
  imagePullSecrets:
    - name: ${IMAGE_REGISTRY_AUTH_SECRET}
  postgresql:
    auth:
      database: harbor_db
      existingSecret: ${SECRET}
      secretKeys:
        adminPasswordKey: ${POSTGRES_ADMIN_PASSWORD_SECRET_KEY}