apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: ${NAMESPACE}-postgresql
  namespace: ${NAMESPACE}
spec:
  instances: 1
  imageName: ${IMAGE_REGISTRY}/${POSTGRESQL_IMAGE_REPOSITORY}:${POSTGRESQL_IMAGE_TAG}
  imagePullSecrets:
    - name: ${IMAGE_REGISTRY_AUTH_SECRET}
  enableSuperuserAccess: true
  bootstrap:
    initdb:
      database: harbor_db
      owner: harbor
      secret:
        name: ${SECRET}
  storage:
    storageClass: ${PERSISTENCE_STORAGE_CLASS}
    size: ${PERSISTENCE_SIZE}
  affinity:
    nodeSelector:
      cosmotech.com/tier: db
    tolerations:
      - key: vendor
        operator: Equal
        value: cosmotech
        effect: NoSchedule
  monitoring:
    enablePodMonitor: true