apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: letsencrypt-prod
  namespace: monitoring
spec:
  secretName: letsencrypt-prod
  dnsNames:
    - ${cluster_domain}
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
