apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: ${email}
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - http01:
        ingress:
          class: nginx
          podTemplate:
            metadata:
              labels:
                networking/traffic-allowed: "yes"     
            spec:
              tolerations:
              - key: "vendor"
                operator: "Equal"
                value: "cosmotech"
                effect: "NoSchedule"
              nodeSelector:
                "cosmotech.com/tier": "services"
