apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-${MAIN_NAME}-scaler-replica-state
  namespace: ${NAMESPACE}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi