image:
  repository: ${IMAGE_REGISTRY}/${IMAGE_REPOSITORY}
  tag: ${IMAGE_TAG}
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: ${IMAGE_PULL_SECRET}

config:
  clusterWide: true

serviceAccount:
  create: true

rbac:
  create: true

webhook:
  mutating:
    create: true
  validating:
    create: true

crds:
  create: true